name = "hy-delta"
main = "index.js"
compatibility_date = "2026-01-01"

[vars]
DELTA_URL = "https://raw.githubusercontent.com/HYnetz/hy-site-pub/gh-pages/current/delta_new.txt"
API_KEYS = "zWA1LrTGnCj89UEAdqMFoRaJ,2TOHMo1IuPnNgnHAF-ftBK6y,4rtwyEwEMe89k2FZgjzOWN8O,tDlgrhpW3abwd9h9_Oy5fZY_,qCxuvJDyKqAkK7v9ygkpLusv,v64ZJ1OGYBgYkmv4i6p_ZcBs,wvGq3jI2QB-d_QXumjJbU1sN,fmBLgE8sYqYTaRal5bUF2jVA,GWpGWSLEheNe7wtOsAWBI4rL,wi7Y-VHHsY4yiTGMwyRnK1lg"
