name = "hy-delta"
main = "index.js"
compatibility_date = "2026-01-01"

[vars]
DELTA_URL = "https://raw.githubusercontent.com/HYnetz/hy-site-pub/gh-pages/current/delta_new.txt"
API_KEYS = "N4iP8hnbHvC7yrRe1T4s0YFK"

META_URL = "https://raw.githubusercontent.com/HYnetz/hy-site-pub/gh-pages/current/meta.json"
